// Code generated by mockery v2.40.1. DO NOT EDIT.

package mocks

import (
	context "context"
	helpers "ticket-service/internal/pkg/helpers"

	mock "github.com/stretchr/testify/mock"

	request "ticket-service/internal/modules/ticket/models/request"
)

// MongodbRepositoryQuery is an autogenerated mock type for the MongodbRepositoryQuery type
type MongodbRepositoryQuery struct {
	mock.Mock
}

// FindOfflineTicketByCountry provides a mock function with given fields: ctx, payload
func (_m *MongodbRepositoryQuery) FindOfflineTicketByCountry(ctx context.Context, payload request.TicketReq) <-chan helpers.Result {
	ret := _m.Called(ctx, payload)

	if len(ret) == 0 {
		panic("no return value specified for FindOfflineTicketByCountry")
	}

	var r0 <-chan helpers.Result
	if rf, ok := ret.Get(0).(func(context.Context, request.TicketReq) <-chan helpers.Result); ok {
		r0 = rf(ctx, payload)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(<-chan helpers.Result)
		}
	}

	return r0
}

// FindOfflineTicketByCountryCode provides a mock function with given fields: ctx, countryCode, tag
func (_m *MongodbRepositoryQuery) FindOfflineTicketByCountryCode(ctx context.Context, countryCode string, tag string) <-chan helpers.Result {
	ret := _m.Called(ctx, countryCode, tag)

	if len(ret) == 0 {
		panic("no return value specified for FindOfflineTicketByCountryCode")
	}

	var r0 <-chan helpers.Result
	if rf, ok := ret.Get(0).(func(context.Context, string, string) <-chan helpers.Result); ok {
		r0 = rf(ctx, countryCode, tag)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(<-chan helpers.Result)
		}
	}

	return r0
}

// FindOnlineTicketByCountry provides a mock function with given fields: ctx, payload
func (_m *MongodbRepositoryQuery) FindOnlineTicketByCountry(ctx context.Context, payload request.TicketReq) <-chan helpers.Result {
	ret := _m.Called(ctx, payload)

	if len(ret) == 0 {
		panic("no return value specified for FindOnlineTicketByCountry")
	}

	var r0 <-chan helpers.Result
	if rf, ok := ret.Get(0).(func(context.Context, request.TicketReq) <-chan helpers.Result); ok {
		r0 = rf(ctx, payload)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(<-chan helpers.Result)
		}
	}

	return r0
}

// FindTicketByLowestPrice provides a mock function with given fields: ctx, tag
func (_m *MongodbRepositoryQuery) FindTicketByLowestPrice(ctx context.Context, tag string) <-chan helpers.Result {
	ret := _m.Called(ctx, tag)

	if len(ret) == 0 {
		panic("no return value specified for FindTicketByLowestPrice")
	}

	var r0 <-chan helpers.Result
	if rf, ok := ret.Get(0).(func(context.Context, string) <-chan helpers.Result); ok {
		r0 = rf(ctx, tag)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(<-chan helpers.Result)
		}
	}

	return r0
}

// NewMongodbRepositoryQuery creates a new instance of MongodbRepositoryQuery. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMongodbRepositoryQuery(t interface {
	mock.TestingT
	Cleanup(func())
}) *MongodbRepositoryQuery {
	mock := &MongodbRepositoryQuery{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
