// Code generated by mockery v2.40.1. DO NOT EDIT.

package mocks

import (
	context "context"
	request "ticket-service/internal/modules/ticket/models/request"

	mock "github.com/stretchr/testify/mock"

	response "ticket-service/internal/modules/ticket/models/response"
)

// UsecaseQuery is an autogenerated mock type for the UsecaseQuery type
type UsecaseQuery struct {
	mock.Mock
}

// FindOnlineTicket provides a mock function with given fields: origCtx, payload
func (_m *UsecaseQuery) FindOnlineTicket(origCtx context.Context, payload request.TicketReq) (*response.Ticket, error) {
	ret := _m.Called(origCtx, payload)

	if len(ret) == 0 {
		panic("no return value specified for FindOnlineTicket")
	}

	var r0 *response.Ticket
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, request.TicketReq) (*response.Ticket, error)); ok {
		return rf(origCtx, payload)
	}
	if rf, ok := ret.Get(0).(func(context.Context, request.TicketReq) *response.Ticket); ok {
		r0 = rf(origCtx, payload)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*response.Ticket)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, request.TicketReq) error); ok {
		r1 = rf(origCtx, payload)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindTickets provides a mock function with given fields: origCtx, payload
func (_m *UsecaseQuery) FindTickets(origCtx context.Context, payload request.TicketReq) (*response.TicketResp, error) {
	ret := _m.Called(origCtx, payload)

	if len(ret) == 0 {
		panic("no return value specified for FindTickets")
	}

	var r0 *response.TicketResp
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, request.TicketReq) (*response.TicketResp, error)); ok {
		return rf(origCtx, payload)
	}
	if rf, ok := ret.Get(0).(func(context.Context, request.TicketReq) *response.TicketResp); ok {
		r0 = rf(origCtx, payload)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*response.TicketResp)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, request.TicketReq) error); ok {
		r1 = rf(origCtx, payload)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewUsecaseQuery creates a new instance of UsecaseQuery. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewUsecaseQuery(t interface {
	mock.TestingT
	Cleanup(func())
}) *UsecaseQuery {
	mock := &UsecaseQuery{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
